Algoritmo "teste_matrizes_00"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/12/2024
Var
// Seção de Declarações das variáveis 

a : vetor [0..2, 0..3] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

a[1, 2] <- 10

Fimalgoritmo